# jekyll configuration

title: "Pinball Arcade Users Guide for Android"
url: "http://jaredmorgs.github.io/Pinball_Arcade_Users_Guide_Android/"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font-awesome

sitemap:
  include_posts: "/default.html, /docs"
# end of configuration
